server {
    listen 443 ssl;
    #listen 443 quic reuseport;
    http2 on;
    #http3 on;
    server_name  _;

    include "/etc/nginx/ssl/default-ssl.conf";

    location / {
        proxy_pass http://api:1234;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        add_header "Access-Control-Allow-Origin" "*";
        # required for browsers to direct them to quic port
        #add_header Alt-Svc 'h3=":443"; ma=86400';
    }

    resolver
        # Cloudflare
        1.1.1.1 1.0.0.1 [2606:4700:4700::1111] [2606:4700:4700::1001]
        # Google
        8.8.8.8 8.8.4.4 [2001:4860:4860::8888] [2001:4860:4860::8844]
        # Quad9
        9.9.9.9 149.112.112.112 [2620:fe::fe] [2620:fe::9]
        valid=60s;
    resolver_timeout 2s;

    # Server software information
    server_tokens off;
}
