# https://github.com/h5bp/server-configs-nginx/blob/main/h5bp/tls/ocsp_stapling.conf

ssl_stapling on;
ssl_stapling_verify on;

# https://github.com/h5bp/server-configs-nginx/blob/main/h5bp/tls/certificate_files.conf
# https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/user-side-certificates/install-cloudflare-cert/

ssl_certificate /etc/nginx/certs/localhost+1.pem;
ssl_certificate_key /etc/nginx/certs/localhost+1-key.pem;
### ONLY IN PROD
#ssl_client_certificate /etc/nginx/certs/cloudflare.crt;
#ssl_verify_client on;

# https://github.com/h5bp/server-configs-nginx/blob/main/h5bp/tls/policy_balanced.conf

ssl_protocols TLSv1.2;
ssl_ciphers EECDH+CHACHA20:EECDH+AES;
ssl_ecdh_curve X25519:prime256v1:secp521r1:secp384r1;

# https://github.com/h5bp/server-configs-nginx/blob/main/h5bp/tls/ssl_engine.conf

ssl_session_timeout 24h;
ssl_session_cache shared:SSL:10m;
keepalive_timeout 300s;
ssl_buffer_size 1400;
ssl_session_tickets off;
ssl_prefer_server_ciphers off;
